site_name: pixelblaze-client documentation

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

plugins:
  - search
  - autorefs
  - mkdocstrings
  - mkapi:
      src_dirs: [ pixelblaze ]

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - admonition

nav:
  - index.md
  - how-to-guides.md
  - pixelblaze.md
  - pixelblazeProtocol.md
  - tutorials.md
  - API: mkapi/api/pixelblaze/pixelblaze
  #- api/pixelblaze.md
