site_name: pixelblaze-client documentation
site_url: https://zranger1.github.io/pixelblaze-client/

theme:
  name: "material"
  #logo: images/logo.svg or logo.png
  features:
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    #- navigation.instant
    #- toc.integrate

plugins:
  - search
  - autorefs
  - mkdocstrings
  - mkapi:
      src_dirs: [ pixelblaze ]
  - social

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - admonition

nav:
  - Home: index.md
  - How-To: how-to-guides.md
  - API: pixelblaze.md
  #- API: mkapi/api/pixelblaze/pixelblaze
  - The Pixelblaze Protocol: pixelblazeProtocol.md
  - Tutorials: tutorials.md
